baseurl = "http://tosatto.me/"
languageCode = "en-us"
title = "Andrea Tosatto"
theme = "detox"
canonifyurls = true
pygmentsuseclasses = true

# Menu Customization
SectionPagesMenu = "main"
[[menu.main]]
   name = "blog"
   weight = -20
   identifier = "posts"  # this must match the section name
   url = "/posts/"
[[menu.main]]
  name = "talks"
  weight = -10
  identifier = "talks"  # this must match the section name
  url = "/talks/"

[blackfriday]
  hrefTargetBlank = true  # open links in new tab

[permalinks]
  talks = "talks/:slug/"
  posts = "posts/:slug/"

[taxonomies]
  tag = "tags"

[params]
  author       = "Andrea Tosatto"
  description  = "Thoughts and stories from a passionate technlogist in love with automation"
  twitter_name = "_hilbert_"
  github_name  = "atosatto"
  google_analytics = "UA-31188191-2"
  custom_css = [
    "/css/simplegrid.css",  # see http://thisisdallas.github.io/Simple-Grid/
    "/css/navbar.css",
    "/css/custom.css",
    "/css/highlight.monokai-sublime.css"
  ] # relative to public directory
  custom_js = [
    "js/highlight.go.min.js"
  ]
